#define BIO_BLOB_TYPE_FUNGUS 1
#define BIO_BLOB_TYPE_FIRE 2
#define BIO_BLOB_TYPE_EMP 3
#define BIO_BLOB_TYPE_TOXIC 4
#define BIO_BLOB_TYPE_RADIOACTIVE 5
#define ALL_BIO_BLOB_TYPES list(BIO_BLOB_TYPE_FUNGUS, BIO_BLOB_TYPE_FIRE, BIO_BLOB_TYPE_EMP, BIO_BLOB_TYPE_TOXIC, BIO_BLOB_TYPE_RADIOACTIVE)

#define MOLD_FACTION "mold"
